language: node_js
node_js: node
deploy: 
  provider: heroku
  api_key:
    secure: FIJivDEQhfWmxj6RcHRIKqkNZIklo9maPIHGzZdjedDNvYR4jJkVsaLvQTTHDFrNfWyGkI6HZj56UFCxFqjSPba2IhzXanFhIoirtsDc2wKhhm0LJfbjfBO1+SLTBlSn2NBZrORhsT/iBd+CPsZr5fzFPGfmyflnl5LUY2zScbU48rWgmvr2wU6d7JMfhlF7Z7hE7Woki8NzQfGpKQ5KW6M1JLY6DhFHy9J8QCfJCxpxQQNDKeocEzUHyKDOxjw0LLxEzj4p07gdPiKibqe780NOFh0uDTFWJP7n8oiv9LiSZugG+lXoe8HNoXA4K8WFp5xchD1l5lBdbSC4kjlcNO+J6JEFKvGbP5LOEDHAMSxsyIyxUjykHP/b71XUtRtk2TgL9N116E2B/3NGOYMOLVXy2mlFp4M74eVn6fIiRcyS2zcZkP384KsvnR8nrOht8ScMWLzTWxdY58uD6MEfyqdBX9CuefSO1eIo/HUB42pJry8E+R4LiF2u1ujQVmFjorx80jxFGUymLtdCxTOH1LxdW9JDZWEMB6f9b79+AIY41OQazKpZfS85Leh/murID4fBUWzgfE72SuHI4Dv/i50Ats8H/rLvRgFt6pcZKK/cuvVOhymmcdDPpDbVJDHudQzsfbB8T49ML3bbqh1F1nzZv8UpDO2EJyv/xmZiJLQ=
  app: https://warm-sands-71651.herokuapp.com/
  on:
    repo: jhoglen1/capstone3
